name: fit_test
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^10.1.2
  retrofit: ^4.0.1
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  get_it: ^7.6.4
  flutter_screenutil: ^5.9.0
  video_player: ^2.7.1
  cached_network_image: ^3.2.3
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  json_serializable: ^6.7.0
  freezed: ^2.4.1
  retrofit_generator: ^7.0.8
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.4
flutter:
  uses-material-design: true
  assets:
    - assets/video/